FROM openquantumsafe/mosquitto:latest

ADD --chown=mosquitto:mosquitto mosquitto_tls.conf /mosquitto/config/mosquitto.conf

COPY --from=iotsim/certificates:latest --chown=mosquitto:mosquitto /artifacts/pki/* /mosquitto/config/

